---
- name: Install NodeJs
  apt: name=nodejs state=latest
- name: Run Application
  shell: |
    cd /home/ubuntu/Ansible-Sample-Application-Deployment/roles/nodejs/files/backend
    npm install
    node server.js
