---
- name: Install NodeJs
  apt: name=nodejs state=latest
- name: Install NPM
  apt: name=npm state=latest
- name: Run Application
  command: ls -ll
  register: result
- debug:
    var: result.stdoutlines
