---
- name: Install NodeJs
  apt: name=nodejs state=latest
- name: Install NPM
  apt: name=npm state=latest
- name: Run Application
  command: pwd
  #command: chdir=Ansible-Sample-Application-Deployment/roles/nodejs/files/backend && npm install && node server.js
