---
- name: Install NodeJs
  apt: name=nodejs state=latest
- name: Install NPM
  apt: name=npm state=latest
- name: Run Application
  # shell: pwd
  # register: playbook_path_output
  #- debug: var=playbook_path_output.stdout_lines
  command: chdir=../files/backend && npm install && node server.js
