---
- name: Install NodeJs
  apt: name=nodejs state=latest
- name: Install NPM
  apt: name=npm state=latest
- name: Copy files to remote machine
  become: true
  copy:
    src: /home/ubuntu/Ansible-Sample-Application-Deployment/roles/nodejs/files/backend
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 0644
- name: Run Application
  command: npm install
  args:
    chdir: /home/ubuntu/backend
    executable: /bin/bash
  register: result
- debug:
    var: result.stdout_lines
