---
- name: Install NodeJs
  apt: name=nodejs state=latest
- name: Install NPM
  apt: name=npm state=latest
- name: Run Application
  command: chdir=/home/ubuntu/Ansible-Sample-Application-Deployment/roles/nodejs/files/backend
